[build]
  base = "frontend"
  publish = "frontend/build"
  command = "cd frontend && npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  CI = "false"
  NODE_VERSION = "18"